version: "3"
services:
    registry:
        image: registry:2.6.2
        ports:
            - "5000:5000"
        volumes:
            - "C:\\Users\\Dev\\Documents\\Docker\\Registry\\config.yml:/etc/docker/registry/config.yml"
        deploy:
            restart_policy:
                condition: on-failure