version: "3"
services:
    hub:
        image: esycat/jetbrains-hub:latest
        ports:
            - "9180:8080"
        volumes:
            - "hub-data:/var/lib/hub"
            - "hub-conf:/opt/hub/conf"
        networks:
            - overlay
        deploy:
            restart_policy:
                condition: on-failure
    upsource:
        image: esycat/upsource:latest
        ports:
            - "9181:8080"
        volumes:
            - "upsource-data:/var/lib/upsource"
            - "upsource-conf:/opt/upsoruce/conf"
        networks:
            - overlay
        deploy:
            restart_policy:
                condition: on-failure

volumes:
    hub-data:
    hub-conf:
    upsource-data:
    upsource-conf:

networks:
  overlay:
    driver: overlay
