version: "3"
services:
    hub:
        image: esycat/jetbrains-hub:latest
        ports:
            - "9180:8080"
        volumes:
            - "hub_data:/var/lib/hub"
            - "hub_conf:/opt/hub/conf"
        networks:
            - overlay
    upsource:
        image: esycat/upsource:latest
        ports:
            - "9181:8080"
        volumes:
            - "upsource_data:/var/lib/upsource"
            - "upsource_conf:/opt/upsoruce/conf"
        networks:
            - overlay
    youtrack:
        image: esycat/youtrack:latest
        ports:
            - "9182:8080"
        volumes:
            - "youtrack_data:/var/lib/youtrack"
            - "youtrack_conf:/opt/youtrack/conf"
        networks:
            - overlay

volumes:
    hub_data:
    hub_conf:
    upsource_data:
    upsource_conf:
    youtrack_data:
    youtrack_conf:

networks:
  overlay:
    driver: overlay
