version: "3"
services:
    master:
        image: jenkinsci/blueocean:latest
        ports:
            - "9080:8080"
            - "50000:50000"
        volumes:
            - "data:/var/jenkins_home"
        networks:
            - overlay
        deploy:
            restart_policy:
                condition: on-failure
        environment:
          JAVA_ARGS : "-Xmx1048m -XX:MaxPermSize=512m"
    worker:
        image: jenkins/jnlp-slave
        environment:
            - JENKINS_URL="http://LTP-48:50000"
        networks:
            - overlay
        deploy:
            replicas: 0

volumes:
    data:

networks:
  overlay:
    driver: overlay
