version: "3"
services:
    master:
        image: jenkinsci/blueocean:latest
        ports:
            - "9080:8080"
            - "50000:50000"
        volumes:
            - "jenkins-data:/var/jenkins_home"            
        networks:
            - overlay
        deploy:
            restart_policy:
                condition: on-failure
    worker:
        image: jenkins/jnlp-slave
        environment:
            - JENKINS_URL="http://jenkins_master:50000"
        networks:
            - overlay
        deploy:
            replicas: 0

volumes:
    jenkins-data:

networks:
  overlay:
    driver: overlay
